var GAME_LEVELS = [
  ["             xxxxx                                       x                        ",
   "             x!!!x                                       |                        ",
   "             x!!!x                                                                ",
   "               v                                                                  ",
   "                                                                                  ",
   "                                                  o         o                     ",
   "                                             o                                    ",
   "                                                  t         t               o     ",
   "                                    o o      t             tt                     ",
   "              o o                                                   o             ",
   "                                   ttttt                                          ",
   "              o o                                                                 ",
   "                                          o           t                           ",
   "                                                                   ttt            ",
   "             x   x      t  =    t         t                                       ",
   "             x!!!x                                                                ",
   "    @        x!!!x                 x           e     x                            ",
   "xxxxxxxxxxxxxx!!!xxxxxxxxxxxxxx    xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx",
   "             xxxxx            x    x                  x     x                     ",
   "                              x!!!!x                  x!!!!!x                     ",
   "                              x!!!!x                  x!!!!!x                     ",
   "                              xxxxxx                  xxxxxxx                     ",
   "                                                                                  "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                             o  o                                                                 ",
   "                                                                                                x                 ",
   "                             o o      t  e              e  t                                    x                 ",
   "                                      tttttttttttttttttttttt       oo                           x                 ",
   "                             ttt               x                                                x                 ",
   "                                     o o       x                   tt      oo                   x                 ",
   "                                               x                                              xxxxx               ",
   "xxxxxxxx        xxxxxxxx         o   ttt       x              o o          tt                  xxx                ",
   "       x        x           o o                x                                                x                 ",
   "       x  o     x                              x     o o      ttt                                                 ",
   "              o         o   ttt                x                                                                  ",
   "                                               x     ttt                                                        ",
   "                x  e    x                      x                                                                  ",
   "      x         xxxxxxxxxx                     x                                                                  ",
   "    @ x         xxxxxxxxxxxx                   x                                                                  ",
   "xxxxxxxxx!!!!!xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxx         xxxxxxxxxxxxx",
   "        x!!!!!x             x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                        x            ", 
   "        x!!!!!x              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                        xx            ",
   "        x!!!!!x               x                    xw    o       x                                 xxx            ",
   "        xxxxxxx                x         o                                                        xxxx            ",
   "                                x e            x                                                 xxxxx            ",
   "                                xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            "],
  ["                                                                                                                       ",
   "                                          x                                                                            ",
   "                                          x                                                                            ",
   "                                          x                                                                            ",
   "                                          x                                                                            ",
   "                                          x                                                                            ",
   "                                          x                                                                            ",
   "                                          x         o                                                                  ",
   "                                          x                                                xxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                          xx o       t       xx ttttt    o o               x                           ",
   "                                          xl                 sx                            x                           ",
   "                                          xl t               sx                            x                           ",
   "                                          xl                 sx          ttt               x                           ",
   "                                          xl     t           sx                 ttt        x                           ",
   "                                          xl                 sx    o o                     x                           ",
   "  x                                       xl        e        sx                                                        ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    ttt                                                 ",
   "  x                                                                                                                    ",
   "  x                                                                      o o                                           ",
   "  x                                                                                                                    ",
   "  x                                                                      ttt             o o                           ",
   "  x                                                    o o                                                             ",
   "  x                                                               o o           o  o                                   ",
   "  x                    o  o                           tttt                               ttt    t   xx           xxxxxx",
   "  x                                     o     o                  tttt                               xl      o    wxxxxx",
   "  x                     t             t e        t                              tttt                xl      o    wxxxxx",
   "  x                                   tttttttttttt                                                  xl      o    wxxxxx",
   "  x                                                                                                 xl      o    wxxxxx",
   "  x           o o o x      x      x                       t                           t             xl      o    wxxxxx",
   "  x      @    o o o xl     wxx    x                       x e          e            e x             xl e        e xxxxx",
   "  xxxxxxxxxxxxxxxxxxx!!!!!!xxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!xxx!!!!!!!!!!!!xxxxx",
   "                    xxxxxxxx      xxxxxxxxxxxxxxxxxxxxxxxxx                            xxxxxxxxxxxxx xxxxxxxxxxxxxxxxxx",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                                       ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "  xxxxxxxxxxx                                                                                                 ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "  x         x   x       x   x       x   x                 ||                  x     x                         ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x                   e                 x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
   ["                                                                       Level 5                               ",
   "                                                                                                              ",
   "                                                                                                              ",]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
